### ISSUE TITLE
Declaring pipe that I generated in angualr 17

### ISSUE THREAD

**Issue by yaelNoifeld** [malbruk/wolf-practicum-2024#17]
I don't find the position to declare a pipe that I generated.
In the instructions you need to declare it in the appModule, but in angular 17 there isn't appModule.
I saw in one place that it was necessary to declare it in the imports of the component, but it doesn't work with it.
I would appreciate an answer, thanks!

**Comment by Nanif** [comment]
באנגולר 17 אין יותר שימוש במודולים.
את צריכה להוסיף את ה pipe ל imports של הקומפוננטה.

[יש לך פה בדיוק את השאלה ששאלת
](https://stackoverflow.com/questions/77519728/how-do-you-register-custom-pipes-in-angular-17
)

**Comment by yaelNoifeld** [comment]
Thank you for the answer! 
but I tried to do it, and this is the error I got:
**The pipe 'FilterPipe' appears in 'imports', but is not standalone and cannot be imported directly. It must be imported via an NgModule.**

**Comment by yaelNoifeld** [comment]
תודה ענקית!!!!!!!!! 
זה עזר לי בטרוף!!!!
