### ISSUE TITLE
 של עובד post שגיאה בשליחה ל

### ISSUE THREAD

**Issue by shulamitv** [malbruk/wolf-practicum-2024#36]
**מידע**
עני על השאלות הבאות:
ש. האם הבאג מתרחש בקליינט או בסרבר?
ת. קליינט
ש. קישור לריפו בגיטהאב (public)
ת. https://github.com/shulamitv/practycum-project-employee/tree/master

**תיאור באג**
רשמי תיאור ממוקד של הבעיה, פרטי כל מידע שיכול להחכים את מי שרוצה לעזור לך...
שגיאת 400 בשליחת עובד חדש להוספה, האובייקט נראה מעולה, ב swager עובד.
וכן בעדכון ומחיקה שגיאת 400 בסרבר עובד מעולה ( שמתאפשרים רק לעובד הנוכחי שנכנס למערכת)
תודה רבה!!

**שחזור מקרה**
רשמי מהם הצעדים שיש לבצע כדי לשחזר את הבעיה:
1. יש להריץ את הקוד 
2. ללחוץ על... כניסה עם המשתמש הזה: shul vander 325955185 ואז הוספת עובד למלא את כל הפרטים ולשלוח
3. וכן במחיקה ועריכה כנ"ל
4.
5. מתקבלת שגיאה- שגיאת 400

**התנהגות תקינה**
רשמי תיאור קצר וממוקד של התנהגות תקינה שאת מצפה לה.
העובד יתווסף (alert)

**קטעי קוד**
העתיקי קטעי קוד רלוונטיים.

**צילומי מסך**
צרפי צילומי מסך של השגיאה או כל דבר שיכול לעזור להבין את המקרה.
![צילום מסך 2024-04-08 002306](https://github.com/malbruk/wolf-practicum-2024/assets/148656448/a0a1ceb5-e0ea-4679-b22f-2149790bbf8c)
/

**הקלטת מסך**
צרפי הקלטת מסך של השגיאה עם הסבר על הבעיה.

**Comment by malkigoelman** [comment]
הסתדרת?
כי גם לי יש את אותה בעיה 
ונראה לי ניסיתי את כל הדרכים לפתרון...
אשמח לשמוע אם יש לך פתרון

**Comment by shulamitv** [comment]
לא הסתדרתי,
אצלי זה כל הקריאות שרת אחרי הלוגין גם לך?
בתחילה זה עבד... עכשיו הסתבך...:)
אין לי בדל של רעיון...

‫בתאריך יום ב׳, 8 באפר׳ 2024 ב-12:02 מאת ‪malki goelman‬‏ <‪
***@***.***‬‏>:‬

**Comment by shulamitv** [comment]
ברוך השם עובד!
