### ISSUE TITLE
שיוך טופס פנימי לטופס חיצוני

### ISSUE THREAD

**Issue by ElishevaR** [malbruk/wolf-practicum-2024#4]
בבחירת תפקיד מסוים עבור עובד נוצר טופס פנימי המשויך לטפס הכללי, הערכים שהמשתמש מכניס בשדות קלט אלו אינם מסונכרנים לטופס הכללי
`
import { Component, OnInit } from '@angular/core';
import { AbstractControl, FormArray, FormBuilder, FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { RoleModel } from '../../../models/role';
import { RoleService } from '../../../services/role.service';
import { CommonModule } from '@angular/common';
import { EmployeeService } from '../../../services/employee.service';
import Swal from 'sweetalert2';
import { Router } from '@angular/router';
import { RoleForEmployeeModel } from '../../../models/roleForEmployeeModel';

@Component({
  selector: 'app-add-employee',
  standalone: true,
  imports: [CommonModule,ReactiveFormsModule],
  templateUrl: './add-employee.component.html',
  styleUrl: './add-employee.component.scss'
})

export class AddEmployeeComponent implements OnInit {
  addEmployeeForm!: FormGroup;
  rolesList: RoleModel[] = [];

  constructor(
    private _employeeService: EmployeeService,
    private _roleService: RoleService,
    private _formBuilder: FormBuilder,
    private _router: Router
  ) {}

  ngOnInit(): void {
    this._roleService.GetRolesLIst().subscribe({
      next: (res) => {
        this.rolesList = res;
      },
      error: (err) => {
        console.error(err);
      }
    });

    this.addEmployeeForm = this._formBuilder.group({
      fName: ['', Validators.required],
      lName: ['', Validators.required],
      identityNumber: ['', Validators.required],
      startDate: ['', Validators.required],
      birthDate: ['', Validators.required],
      gender: [0, Validators.required],
      isActivate: [false, Validators.required],
      preferRoles: this._formBuilder.array([])
    });
  }

  addEmployee(): void {
    this._employeeService.register(this.addEmployeeForm.value).subscribe({
      next: (res) => {
        Swal.fire({
          title: 'Thank you!',
          text: 'The employee was successfully added!',
          icon: 'success'
        });
        this._router.navigate(['employees']);
      },
      error: (err) => {
        console.error(err);
      }
    });
  }

  createRoleFormGroup(role: RoleModel): FormGroup {
    return this._formBuilder.group({
      roleId: [role.id],
      startDateRole: ['',Validators.required],
      isAdmin: [false,Validators.required]
    });
  }

  updateRoleFields(roleId: number, event: Event): void {
    const target = event.target as HTMLInputElement;
    const isChecked = target.checked;
  
    const role = this.rolesList.find(role => role.id === roleId);
  
    if (isChecked && role) {
      const newRoleFormGroup = this.createRoleFormGroup(role);
      (this.addEmployeeForm.get('preferRoles') as FormArray).push(newRoleFormGroup);
    } else {
      const roleIndex = (this.addEmployeeForm.get('preferRoles') as FormArray).controls.findIndex(control => control.value.roleId === roleId);
      if (roleIndex !== -1) {
        (this.addEmployeeForm.get('preferRoles') as FormArray).removeAt(roleIndex);
      }
    }
  }

  findRoleControl(roleId: number): AbstractControl<any> | null {
    const control = (this.addEmployeeForm.get('preferRoles') as FormArray).controls.find(control => control.value.roleId === roleId);
    return control !== undefined ? control : null;
  }
}
}<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <title>Bootstrap Example</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<form [formGroup]="addEmployeeForm" (ngSubmit)="addEmployee()">
  
  <label>First Name:</label>
  <input type="text" formControlName="fName">
  <div *ngIf="addEmployeeForm.get('fName')?.invalid && addEmployeeForm.get('fName')?.touched">
    <p>This field is required!</p>
  </div>

  
  <label>Last Name:</label>
  <input type="text" formControlName="lName">
  <div *ngIf="addEmployeeForm.get('lName')?.invalid && addEmployeeForm.get('lName')?.touched">
    <p>This field is required!</p>
  </div>

  
  <label>Identity Number:</label>
  <input type="text" formControlName="identityNumber">
  <div *ngIf="addEmployeeForm.get('identityNumber')?.invalid && addEmployeeForm.get('identityNumber')?.touched">
    <p>This field is required!</p>
  </div>

  
  <label>Start Date:</label>
  <input type="date" formControlName="startDate">
  <div *ngIf="addEmployeeForm.get('startDate')?.invalid && addEmployeeForm.get('startDate')?.touched">
    <p>This field is required!</p>
  </div>

  
  <label>Birth Date:</label>
  <input type="date" formControlName="birthDate">
  <div *ngIf="addEmployeeForm.get('birthDate')?.invalid && addEmployeeForm.get('birthDate')?.touched">
    <p>This field is required!</p>
  </div>

  
  <label>Gender:</label>
  <select formControlName="gender">
    <option [ngValue]="0">Male</option>
    <option [ngValue]="1">Female</option>
  </select>
  <div *ngIf="addEmployeeForm.get('gender')?.invalid && addEmployeeForm.get('gender')?.touched">
    <p>This field is required!</p>
  </div>

  
  <label>Is Active:</label>
  <input type="checkbox" formControlName="isActivate">

 <div *ngFor="let role of rolesList"><h1> {{ role.description }}</h1></div>
  <div formArrayName="preferRoles">
    <div *ngFor="let role of rolesList">
      <div [formGroupName]="role.id">
        <label>
          <input type="checkbox" (change)="updateRoleFields(role.id, $event)">
          {{ role.description }}
        </label>
        <div *ngIf="findRoleControl(role.id)">
          
          <div>
            <label>Start Date Role:</label>
            <input type="date" formControlName="startDateRole">
          </div> 
          <div>
            <label>Is Admin:</label>
            <input type="checkbox" formControlName="isAdmin">
          </div>
        </div>
      </div>
    </div>
  </div>
  <p>Form status: {{ addEmployeeForm.status }}</p>
  
  <button type="submit" >Submit</button>
</form>`
בבחירת תפקיד מסוים נוצר טופס פנימי המשויך לטפס הכללי, הערכים שהמשתמש מכניס בשדות קלט אלו אינם מסונכרנים לטופס הכללי

**Comment by malbruk** [comment]
@ElishevaR 

סורי, אין לי שום דרך להתחיל להסתכל על הדבר הזה.
האם מדובר בבאג או בשאלה?
אם זה באג, תפתחי באג ותעני מסודר על השאלות.
בהצלחה!
