### ISSUE TITLE
שגיאה בטרמינל בעת הרצה, אנגולר

### ISSUE THREAD

**Issue by ruth7873** [malbruk/wolf-practicum-2024#9]
**מידע**
עני על השאלות הבאות:
ש. האם הבאג מתרחש בקליינט או בסרבר?
ת. קליינט
ש. קישור לריפו בגיטהאב (public)
ת. https://github.com/ruth7873/EmployeeApplication/tree/main

**תיאור באג**
רשמי תיאור קצר וממוקד של הבעיה.
בעת הרצת הפרויקט נוצרת השגיאה הזו בטרמינל, השגיאה אמנם אינה מפריעה להרצה,
 אבל אני לא מבינה מה היא.
ERROR HttpErrorResponse {
  headers: _HttpHeaders {
    normalizedNames: Map(0) {},
    lazyUpdate: null,
    headers: Map(0) {}
  },
  status: 0,
  statusText: 'Unknown Error',
  url: 'https://localhost:7020/api/Employee',
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure response for https://localhost:7020/api/Employee: 0 Unknown Error',
  error: ProgressEvent2 {
    type: 'error',
    target: XMLHttpRequest2 {
      onloadstart: null,
      onprogress: null,
      onabort: null,
      onerror: null,
      onload: null,
      ontimeout: null,
      onloadend: null,
      _listeners: [Object],
      onreadystatechange: null,
      _anonymous: undefined,
      readyState: 4,
      response: null,
      responseText: '',
      responseType: 'text',
      responseURL: '',
      status: 0,
      statusText: '',
      timeout: 0,
      upload: [XMLHttpRequestUpload],
      _method: 'GET',
      _url: [Url],
      _sync: false,
      _headers: [Object],
      _loweredHeaders: [Object],
      _mimeOverride: null,
      _request: null,
      _response: null,
      _responseParts: null,
      _responseHeaders: null,
      _aborting: null,
      _error: null,
      _loadedBytes: 0,
      _totalBytes: 0,
      _lengthComputable: false
    },
    currentTarget: XMLHttpRequest2 {
      onloadstart: null,
      onprogress: null,
      onabort: null,
      onerror: null,
      onload: null,
      ontimeout: null,
      onloadend: null,
      _listeners: [Object],
      onreadystatechange: null,
      _anonymous: undefined,
      readyState: 4,
      response: null,
      responseText: '',
      responseType: 'text',
      responseURL: '',
      status: 0,
      statusText: '',
      timeout: 0,
      upload: [XMLHttpRequestUpload],
      _method: 'GET',
      _url: [Url],
      _sync: false,
      _headers: [Object],
      _loweredHeaders: [Object],
      _mimeOverride: null,
      _request: null,
      _response: null,
      _responseParts: null,
      _responseHeaders: null,
      _aborting: null,
      _error: null,
      _loadedBytes: 0,
      _totalBytes: 0,
      _lengthComputable: false
    },
    lengthComputable: false,
    loaded: 0,
    total: 0
  }
}
ERROR HttpErrorResponse {
  headers: _HttpHeaders {
    normalizedNames: Map(0) {},
    lazyUpdate: null,
    headers: Map(0) {}
  },
  status: 0,
  statusText: 'Unknown Error',
  url: 'https://localhost:7020/api/Role',
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure response for https://localhost:7020/api/Role: 0 Unknown Error',
  error: ProgressEvent2 {
    type: 'error',
    target: XMLHttpRequest2 {
      onloadstart: null,
      onprogress: null,
      onabort: null,
      onerror: null,
      onload: null,
      ontimeout: null,
      onloadend: null,
      _listeners: [Object],
      onreadystatechange: null,
      _anonymous: undefined,
      readyState: 4,
      response: null,
      responseText: '',
      responseType: 'text',
      responseURL: '',
      status: 0,
      statusText: '',
      timeout: 0,
      upload: [XMLHttpRequestUpload],
      _method: 'GET',
      _url: [Url],
      _sync: false,
      _headers: [Object],
      _loweredHeaders: [Object],
      _mimeOverride: null,
      _request: null,
      _response: null,
      _responseParts: null,
      _responseHeaders: null,
      _aborting: null,
      _error: null,
      _loadedBytes: 0,
      _totalBytes: 0,
      _lengthComputable: false
    },
    currentTarget: XMLHttpRequest2 {
      onloadstart: null,
      onprogress: null,
      onabort: null,
      onerror: null,
      onload: null,
      ontimeout: null,
      onloadend: null,
      _listeners: [Object],
      onreadystatechange: null,
      _anonymous: undefined,
      readyState: 4,
      response: null,
      responseText: '',
      responseType: 'text',
      responseURL: '',
      status: 0,
      statusText: '',
      timeout: 0,
      upload: [XMLHttpRequestUpload],
      _method: 'GET',
      _url: [Url],
      _sync: false,
      _headers: [Object],
      _loweredHeaders: [Object],
      _mimeOverride: null,
      _request: null,
      _response: null,
      _responseParts: null,
      _responseHeaders: null,
      _aborting: null,
      _error: null,
      _loadedBytes: 0,
      _totalBytes: 0,
      _lengthComputable: false
    },
    lengthComputable: false,
    loaded: 0,
    total: 0
  }
}

**שחזור מקרה**
רשמי מהם הצעדים שיש לבצע כדי לשחזר את הבעיה:
1. יש להריץ את הקוד - ng s
2. ללחוץ על...
3. מתקבלת שגיאה

**התנהגות תקינה**
רשמי תיאור קצר וממוקד של התנהגות תקינה שאת מצפה לה.

**קטעי קוד**
העתיקי קטעי קוד רלוונטיים.

**צילומי מסך**
צרפי צילומי מסך של השגיאה או כל דבר שיכול לעזור להבין את המקרה.
![צילום מסך 2024-04-04 121643](https://github.com/malbruk/wolf-practicum-2024/assets/149601646/0c5a5a3b-c0e1-4ea8-9545-ff58ef287f9c)

**הקלטת מסך**
צרפי הקלטת מסך של השגיאה עם הסבר על הבעיה.

**Comment by Nanif** [comment]
נסי קודם כל לשים console.log / debugger בפונקצית getAllEmployees 
כדי לראות האם מאיזושהי סיבה את מזמנת את הפונקציה בטעינת האפליקציה.

**Comment by ruth7873** [comment]
בעצם לא, זה עדיין אותה שגיאה

**Comment by Nanif** [comment]
השגיאה הזו בקליאנט?
הרצתי את הפרויקט שלך לוקלית והכל תקין:
![image](https://github.com/malbruk/wolf-practicum-2024/assets/40644835/24646cd6-5165-46b3-976a-5cabc4856def)

**Comment by ruth7873** [comment]
כן, אחרי קצת זמן זה פתאום נהיה
אני לא מצליחה להבין מה גורם לזה.

‫בתאריך יום ה׳, 4 באפר׳ 2024 ב-16:51 מאת ‪Neomi Fishbein‬‏ <‪
***@***.***‬‏>:‬

**Comment by Nanif** [comment]
מה זה אחרי קצת זמן? אחרי פעולה מסוימת?
אם את לא מבצעת שום פעולה באפליקציה שלך זה פתאום יופיע?
נסי להבין את הטריגר לאירוע, האם זה תלוי זמן או בגלל פעולה מסוימת.
כי בתיאור הבאג היה נשמע ממך שזה קורה בטעינה של האפליקציה
ועכשיו את כותבת שזה קורה בדיליי אחרי הטעינה
